In [1]:
import numpy as np

data = [[1, 3, 5, 9], [7, 4, 2, 9]]
arr2 = np.array(data)
print(arr2.ndim) 
print(arr2.shape)  

2
(2, 4)


In [2]:
array = np.array([[1,5,0],[7,3,9]])

In [3]:
array

array([[1, 5, 0],
       [7, 3, 9]])

In [4]:
array = np.eye(3)

In [5]:
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
array = np.zeros((2,3))

In [7]:
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
array = np.arange(0, 4, 6)

In [9]:
array

array([0])

In [11]:
array = np.ones((3,3))

In [12]:
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
array = np.random.randint(0, 9, (2,3))

In [14]:
array

array([[7, 5, 8],
       [7, 2, 2]])

In [15]:
arr = np.array([[9., 6., 10.], [6., 3., 8.]])
print(arr)

[[ 9.  6. 10.]
 [ 6.  3.  8.]]


In [16]:
print(arr * arr)

[[ 81.  36. 100.]
 [ 36.   9.  64.]]


In [17]:
print(arr - arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr = np.array([[9., 6., 10.], [6., 3., 8.]])
print(arr)

[[ 9.  6. 10.]
 [ 6.  3.  8.]]


In [20]:
print(arr **2)

[[ 81.  36. 100.]
 [ 36.   9.  64.]]


In [21]:
arr2 = np.array([[6., 9., 5.], [10., 6., 12.]])
print(arr2)

[[ 6.  9.  5.]
 [10.  6. 12.]]


In [22]:
print(arr2 > arr)

[[False  True False]
 [ True  True  True]]


In [23]:
arr = np.arange(10)
print(arr) 

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(arr[7])

7


In [25]:
print(arr[5:8])

[5 6 7]


In [26]:
arr[5:8] = 11
print(arr)

[ 0  1  2  3  4 11 11 11  8  9]


In [27]:
arr = np.arange(10)
print(arr)   

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr_slice = arr[5:8]
print(arr_slice)

[5 6 7]


In [29]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4     5 12345     7     8     9]


In [30]:
arr_slice[:] = 52
print(arr)

[ 0  1  2  3  4 52 52 52  8  9]


In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])       

[7 8 9]


In [33]:
print(arr2d[0][2])    

3


In [34]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [35]:
arr2d_slice = arr2d[:, -1]
print(arr2d_slice)

[3 6 9]


In [36]:
arr2d_slice = arr2d[1, -2:]
print(arr2d_slice)

[5 6]
